In [3]:
import numpy as np

In [2]:
my_list = [1,2,3,54,5,6]

In [4]:
x = np.array(my_list)

In [5]:
type(x)

numpy.ndarray

In [6]:
my_matrix = [[1,2,4], [3,4,5], [7,8,9]]

In [7]:
np.array(my_matrix) # basically finance data is 2D

array([[1, 2, 4],
       [3, 4, 5],
       [7, 8, 9]])

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [9]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
np.zeros(4) # floating point always 

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.linspace(1,3,5) # gives evenly spaced numbers

array([1. , 1.5, 2. , 2.5, 3. ])

In [19]:
np.eye(4) # square matrix - same number of the rows and columns 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(4) # give number between 0 and 1

array([0.22254403, 0.62915428, 0.10924002, 0.07178874])

In [21]:
np.random.rand(2,2)

array([[0.96912342, 0.1164757 ],
       [0.04153515, 0.16846457]])

In [22]:
np.random.randn(5) # 5 numbers chosen from the random normal distribution

array([ 0.0646563 , -0.36024503,  0.77384036, -0.50861085,  0.50580868])

In [23]:
np.random.randint(1,100)

70

In [25]:
np.random.randint(1,100,5)# gives five random numbers

array([28, 57, 37, 79, 63])

In [26]:
arr = np.arange(1,10)
ranarr = np.random.randint(1,10,8)

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ranarr

array([7, 8, 6, 4, 1, 9, 3, 2])

In [32]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(9,)

In [35]:
arr.reshape(3,3).shape

(3, 3)

In [40]:
arr.reshape(9,1).shape

(9, 1)

In [41]:
arr.max()

9

In [44]:
arr.argmax() # index value of the maximum value

8

In [45]:
# numpy array differs from normal ones because of the ability to broadcast

In [49]:
arr1 = np.arange(1,20)

In [50]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [51]:
slice_of_arr1 = arr1[1:6]

In [52]:
slice_of_arr1

array([2, 3, 4, 5, 6])

In [53]:
slice_of_arr1[:] = 100 # this is broadcasting.

In [54]:
slice_of_arr1

array([100, 100, 100, 100, 100])

In [55]:
# Conditional selections
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [56]:
bool_arr = arr > 4

In [57]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])